name: pr-assign-author

permissions:
  contents: read

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  run:
    uses: crazy-max/.github/.github/workflows/pr-assign-author.yml@d6328d9b95dd248243146d986e1113d5e1738206
    permissions:
      contents: read
      pull-requests: write
